### PR TITLE
Update reference to WOW codebase to make use of new SQL code

### PR DESCRIPTION
**Pull request by sraby**
This PR updates our reference to the newest version of WOW so that we can use a new version of our SQL code that generates the `wow_bldgs` table (which now includes most recent sale data).

### CODE REVIEW

**Comment by toolness** [comment]
Hmm, I'm gonna try debugging this by using less recent WoW revisions until the `test_wowutil` tests pass.

I'm editing the `WOW_REV` in `Dockerfile` and running the following:

```
docker-compose build && docker-compose run app pytest tests/test_wowutil.py
```

So the revision used in this PR, JustFixNYC/who-owns-what@10286cb43645040e67a4c4044d185712671c4589 is giving us the same error that CircleCI is giving us:

```
psycopg2.ProgrammingError: relation "temp_wow_1590146577.hpd_registrations_with_contacts" does not exist
```

It looks like JustFixNYC/who-owns-what@b8b66a03ea025cbb2f8b025aa86dbe94026c2a1a is failing with a different error:

```
ValueError: Table wow.HPD_REGISTRATIONS_WITH_CONTACTS does not exist!
```

Going to its immediate parent, JustFixNYC/who-owns-what@b9878f60bfcaf1993f341ec44d53e30f004bbb09, works fine though, so it's definitely something in these two commits that's making the tests break.

I'm going to take a closer look at these two commits to see what might be causing the problems.

**Comment by sraby** [comment]
Thanks so much for looking into this @toolness! Yes, I remember the tests failing with both of those commits. The first time it failed, the error message 
```ValueError: Table wow.HPD_REGISTRATIONS_WITH_CONTACTS does not exist!``` actually made sense as I had transformed all the SQL code to uppercase and I wasn't aware that references to table names may be case sensitive. The second one is really where I got stumped.

**Comment by toolness** [comment]
Ok, so it looks like the problem has to do with the way that the loader tries to figure out what tables a SQL file is creating by parsing it.  This basically needs to be done in order to be able to load the new data into a temporary schema (same concept as a "folder") while still allowing the old data to be queried...  Normally the parser thinks that WoW is only creating a table called `wow_bldgs`, which is true, but when it looks at your new code, for some reason it thinks it's creating a table called `hpd_registrations_with_contacts`, which is obviously false.  I'm going to fix the parser and then everything should be ok!

**Comment by toolness** [comment]
On the plus side, this isn't just annoying work we have to do to get the tests to pass; if we had just merged this code without those tests being there, the daily WoW update job would have started crashing!  So at least we're preventing something bad from happening in production.

**Comment by toolness** [comment]
Ok sorry about that, I just fixed it, everything should be good now!

**Comment by sraby** [comment]
Thank you so much Mr. @toolness!! Definitely a silver lining here to know that your testing prevented a major crash in our auto-updating instance of the db— good reminder as to why we prioritize our testing capabilities too.

And hmmm, I wonder if the introduction of the new `WITH` statements at the beginning of the updated SQL code (to generate subqueries in a more readable way) may have confused the parser, as that is really the only structural change to the query that was implemented. 

Anyway, glad to know this is resolved and will hopefully avoid similar issues in the future! Can't thank you enough :)

**Pull request merged**
